# MLOps Pipeline Configuration
# This file contains default configuration for the MNIST MLOps pipeline

# Experiment settings
experiment_name: "mnist_cnn_experiment"
random_seed: 42
output_dir: "artifacts"
save_intermediate_results: true

# Data loading configuration
data:
  data_dir: "./data"
  batch_size: 64
  validation_split: 0.1
  num_workers: 4
  pin_memory: true
  download: true
  transform_config: null

# Model architecture configuration
model:
  num_classes: 10
  input_channels: 1
  conv_channels: [32, 64, 128]
  fc_hidden_dims: [256, 128]
  dropout_rate: 0.5
  use_batch_norm: true
  activation: "relu"

# Training configuration
training:
  epochs: 10
  learning_rate: 0.001
  optimizer: "adam"
  scheduler: "plateau"
  scheduler_params: {}
  criterion: "cross_entropy"
  early_stopping_patience: 5
  save_checkpoints: true
  checkpoint_dir: "artifacts/models/checkpoints"
  save_best_only: true
  validation_frequency: 1
  device: "auto"
  mixed_precision: false
  gradient_clip_val: null

# Evaluation configuration
evaluation:
  device: "auto"
  batch_size: 64
  num_classes: 10
  class_names: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
  save_predictions: true
  save_probabilities: true
  calculate_roc_auc: true
  detailed_report: true

# Model release thresholds
release_thresholds:
  min_accuracy: 0.95
  min_precision: 0.9
  min_recall: 0.9
  min_f1_score: 0.9
  max_loss: 0.2
  min_per_class_accuracy: 0.8
  max_inference_time_ms: 100.0
  min_confidence_threshold: 0.7

# Logging configuration
logging:
  log_level: "INFO"
  log_file: null
  log_format: null
  console_logging: true
  file_logging: false